# 模型配置文件
# 此文件定义了可用的AI模型及其配置

# 模型列表
[[models]]
id = "deepseek/deepseek-chat"
name = "DeepSeek Chat"
description = "DeepSeek Chat是一个通用的对话模型，适合日常对话和一般任务"

[[models]]
id = "deepseek/deepseek-reason"
name = "DeepSeek Reason"
description = "DeepSeek Reason是一个专注于推理能力的模型，适合需要逻辑分析的任务"

[[models]]
id = "openrouter/qwen/qwq-32b:free"
name = "QwQ 32B"
description = "QwQ 32B 是一个大规模预训练模型，提供免费使用的版本，适合多种复杂任务"

# 任务配置
[tasks]

[tasks.process_with_llm]
available_models = [
    "deepseek/deepseek-chat",
    "deepseek/deepseek-reason",
    "openrouter/qwen/qwq-32b:free"
]
default_model = "deepseek/deepseek-chat"
description = "使用LLM处理文本内容的任务"

[tasks.process_with_llm.default_config]
temperature = 0.7
max_tokens = 2000
top_p = 0.95

[tasks.ai_review]
available_models = [
    "deepseek/deepseek-reason",
    "openrouter/qwen/qwq-32b:free"
]
default_model = "deepseek/deepseek-reason"
description = "AI审阅和分析文档的任务"

[tasks.ai_review.default_config]
temperature = 0.3
max_tokens = 4000
top_p = 0.9

[tasks.text_summarization]
available_models = [
    "deepseek/deepseek-chat",
    "openrouter/qwen/qwq-32b:free"
]
default_model = "deepseek/deepseek-chat"
description = "文本摘要生成任务"

[tasks.text_summarization.default_config]
temperature = 0.5
max_tokens = 1000
top_p = 0.9

[tasks.extract_structured_data]
available_models = [
    "deepseek/deepseek-reason",
    "openrouter/qwen/qwq-32b:free"
]
default_model = "deepseek/deepseek-reason"
description = "从文本中提取结构化数据的任务"

[tasks.extract_structured_data.default_config]
temperature = 0.2
max_tokens = 3000
top_p = 0.8
extraction_prompt = """请从以下审阅报告中提取结构化数据，以YAML格式返回：

1. 摘要
2. 结构评分 (1-10)
3. 内容完整性评分 (1-10)
4. 语言表达评分 (1-10)
5. 专业性评分 (1-10)
6. 格式规范评分 (1-10)
7. 总体评分 (1-10)
8. 问题清单 (列表)
9. 改进建议 (列表)

使用以下YAML格式：

```yaml
summary: 简短摘要
structure_score: 7
completeness_score: 8
language_score: 9
professionalism_score: 7
format_score: 8
overall_score: 8
issues:
  - 第一个问题
  - 第二个问题
suggestions:
  - 第一个建议
  - 第二个建议
```

审阅报告:""" 