"""remove_structured_data_from_ai_reviews

Revision ID: 649318d463ed
Revises: ae59714e2354
Create Date: 2025-02-23 22:18:25.021937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '649318d463ed'
down_revision: Union[str, None] = 'ae59714e2354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_review_reports', 'structured_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_review_reports', sa.Column('structured_data', sqlite.JSON(), nullable=True))
    # ### end Alembic commands ###
