"""remove_schema_and_fields_columns

Revision ID: ae59714e2354
Revises: b833f71b487d
Create Date: 2025-02-23 15:15:22.060680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'ae59714e2354'
down_revision: Union[str, None] = 'b833f71b487d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_types', 'schema_prompt')
    op.drop_column('article_types', 'fields')
    op.drop_column('projects', 'schema_prompt')
    op.drop_column('projects', 'fields')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('fields', sqlite.JSON(), nullable=True))
    op.add_column('projects', sa.Column('schema_prompt', sa.VARCHAR(), nullable=True))
    op.add_column('article_types', sa.Column('fields', sqlite.JSON(), nullable=True))
    op.add_column('article_types', sa.Column('schema_prompt', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
