"""add auto_approve to project

Revision ID: b6100a08d447
Revises: 303b9237df5c
Create Date: 2024-12-27 15:10:08.455878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6100a08d447'
down_revision: Union[str, None] = '303b9237df5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('auto_approve', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'auto_approve')
    # ### end Alembic commands ###
