"""add_updated_at_to_jobs

Revision ID: b833f71b487d
Revises: 5e5d6d536256
Create Date: 2025-02-15 20:51:55.911225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b833f71b487d'
down_revision: Union[str, None] = '5e5d6d536256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
