"""add schema_prompt field

Revision ID: e93c0b27118a
Revises: 917c12381be9
Create Date: 2024-12-27 18:53:35.895426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e93c0b27118a'
down_revision: Union[str, None] = '917c12381be9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_types', sa.Column('schema_prompt', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('schema_prompt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'schema_prompt')
    op.drop_column('article_types', 'schema_prompt')
    # ### end Alembic commands ###
