"""add_default_empty_string_to_prompts

Revision ID: f00794b71eb5
Revises: 7823b18bc4b1
Create Date: 2024-12-27 21:16:48.307901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f00794b71eb5'
down_revision: Union[str, None] = '7823b18bc4b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
